/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Exam;

import Classes.Exam;
import Classes.Subject;
import DatabaseOperation.ClassDB;
import DatabaseOperation.ExamDB;
import DatabaseOperation.SubjectDB;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mbiuu
 */
public class ExamFrame extends javax.swing.JFrame {
    DefaultComboBoxModel<Classes.Class> cboClassModel;
    DefaultComboBoxModel<String> cboSubjectModel;
    ArrayList<Subject> listSubject;
    ArrayList<Classes.Class> listClass;
    DefaultTableModel tableModel;
    private boolean btnAddDisabled = false;
    private boolean btnEditDisabled = true;
    /**
     * Creates new form ExamFrame
     */
    public ExamFrame() {
        initComponents();
        this.setDefaultCloseOperation(ExamFrame.DISPOSE_ON_CLOSE);
        listSubject = new ArrayList<>();
        listClass = new ArrayList<>();
        cboClassModel = new DefaultComboBoxModel<>();
        cboSubjectModel = new DefaultComboBoxModel<>();
        tableModel = new DefaultTableModel();
        jComboBox1.setModel(cboClassModel);
        cboSubject.setModel(cboSubjectModel);
        loadClassForCombo();
        loadSubjectForCombo();
        tableModel = new DefaultTableModel();
        tableModel.addColumn("ID");
        tableModel.addColumn("Exam Name");
        tableModel.addColumn("Date");
        tableModel.addColumn("Total marks");
        tableModel.addColumn("Condition");
        tableModel.addColumn("Subject name");
        TblExam.setModel(tableModel);
        loadDataForTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtExamID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtExamName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtCondition = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTotalMark = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        cboSubject = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblExam = new javax.swing.JTable();
        btnAdd = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnClear = new javax.swing.JLabel();
        btnManageMark = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(110, 89, 222));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-test-passed-50.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Miriam Mono CLM", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Exam Management");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(99, 78, 254));
        jLabel1.setText("Exam ID");

        txtExamID.setEditable(false);
        txtExamID.setBackground(new java.awt.Color(254, 254, 254));
        txtExamID.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        txtExamID.setText("*");
        txtExamID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 78, 254), 2));

        jLabel2.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(99, 78, 254));
        jLabel2.setText("ExamName");

        txtExamName.setBackground(new java.awt.Color(254, 254, 254));
        txtExamName.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        txtExamName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 78, 254), 2));

        jLabel3.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(99, 78, 254));
        jLabel3.setText("Date");

        txtDate.setEditable(false);
        txtDate.setBackground(new java.awt.Color(254, 254, 254));
        txtDate.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        txtDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 78, 254), 2));

        txtCondition.setBackground(new java.awt.Color(254, 254, 254));
        txtCondition.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        txtCondition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 78, 254), 2));

        jLabel4.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(99, 78, 254));
        jLabel4.setText("Condition(%)");

        txtTotalMark.setBackground(new java.awt.Color(254, 254, 254));
        txtTotalMark.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        txtTotalMark.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(99, 78, 254), 2));

        jLabel5.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(99, 78, 254));
        jLabel5.setText("Total marks");

        jLabel6.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(99, 78, 254));
        jLabel6.setText("Subject");

        jLabel7.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(99, 78, 254));
        jLabel7.setText("Class");

        jComboBox1.setBackground(new java.awt.Color(254, 254, 254));
        jComboBox1.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(99, 78, 254), 2, true));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        cboSubject.setBackground(new java.awt.Color(254, 254, 254));
        cboSubject.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        cboSubject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboSubject.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(99, 78, 254), 2, true));

        jDateChooser1.setBackground(new java.awt.Color(254, 254, 254));
        jDateChooser1.setBorder(null);
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtExamID, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExamName, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotalMark, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(cboSubject, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExamID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel7))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExamName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalMark, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cboSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TblExam.setFont(new java.awt.Font("Miriam Mono CLM", 1, 18)); // NOI18N
        TblExam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblExam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblExamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblExam);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_add.png"))); // NOI18N
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_edit (2).png"))); // NOI18N
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_clear.png"))); // NOI18N
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        btnManageMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-mark (1).png"))); // NOI18N
        btnManageMark.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageMarkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)
                        .addGap(18, 18, 18)
                        .addComponent(btnManageMark, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd)
                    .addComponent(btnEdit)
                    .addComponent(btnClear)
                    .addComponent(btnManageMark))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
       JComboBox<Subject> cb =  (JComboBox) evt.getSource();
        Object item = evt.getItem();

        if (evt.getStateChange() == ItemEvent.SELECTED) {
          // Item was just selected
          tableModel.setRowCount(0);
            loadDataForTable();
//            System.out.println(item.toString());
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
          // Item is no longer selected
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void TblExamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblExamMouseClicked
        // TODO add your handling code here:
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_edit.png")));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_add (2).png")));        
        btnManageMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-mark.png"))); 
        btnAddDisabled = true;
        btnEditDisabled = false;
        int row = TblExam.getSelectedRow();
        txtExamID.setText(TblExam.getValueAt(row, 0)+"");
        txtExamName.setText(TblExam.getValueAt(row, 1)+"");
        txtDate.setText(TblExam.getValueAt(row, 2)+"");
        txtCondition.setText(TblExam.getValueAt(row, 4)+"");
        txtTotalMark.setText(TblExam.getValueAt(row, 3)+"");
        cboSubject.setSelectedItem(TblExam.getValueAt(row, 5)+"");
        
        jComboBox1.setEnabled(false);
    }//GEN-LAST:event_TblExamMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        if(btnAddDisabled == true){           
        }
        else if(validateForm()){
            Exam e = new Exam();
            e.setClass_id(listClass.get(jComboBox1.getSelectedIndex()).getClassID());
            e.setCondition(Integer.parseInt(txtCondition.getText()));
            e.setTotalmark(Integer.parseInt(txtTotalMark.getText()));
            e.setName(txtExamName.getText());
            e.setSubject_id(listSubject.get(cboSubject.getSelectedIndex()).getSubject_id());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            try {
                e.setExam_date(new java.sql.Date(date.parse(txtDate.getText()).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            int eID = new ExamDB().insertExam(e);
            txtExamID.setText(eID+"");
//            loadDataForTable();
            Object[] data = {eID, jComboBox1.getSelectedItem()+"",
                txtDate.getText(),e.getTotalmark(),e.getCondition(),cboSubject.getSelectedItem()+""};
            tableModel.addRow(data);
        }
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_edit (2).png")));
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_add.png")));        
        btnManageMark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/button_manage-mark (1).png"))); 
        btnAddDisabled = false;
        btnEditDisabled = true;
        TblExam.removeRowSelectionInterval(0, TblExam.getRowCount()-1);
        txtExamID.setText("*");
        txtDate.setText("");
        txtExamName.setText("");
        txtCondition.setText("");
        txtTotalMark.setText("");    
        jComboBox1.setEnabled(true);
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        if(btnEditDisabled == true){
            
        }else if(validateForm()){
            Exam e = new Exam();
            int row = TblExam.getSelectedRow();
            e.setClass_id(listClass.get(jComboBox1.getSelectedIndex()).getClassID());
            e.setCondition(Integer.parseInt(txtCondition.getText()));
            e.setTotalmark(Integer.parseInt(txtTotalMark.getText()));
            e.setName(txtExamName.getText());
            e.setSubject_id(listSubject.get(cboSubject.getSelectedIndex()).getSubject_id());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            try {
                e.setExam_date(new java.sql.Date(date.parse(txtDate.getText()).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            e.setExam_id(Integer.parseInt(txtExamID.getText()));
            new ExamDB().editExam(e);
            TblExam.setValueAt(txtExamID.getText(), row, 0);
            TblExam.setValueAt(txtExamName.getText(), row, 1);
            TblExam.setValueAt(txtDate.getText(), row, 2);
            TblExam.setValueAt(txtTotalMark.getText(), row, 3);            
            TblExam.setValueAt(txtCondition.getText(), row, 4);
            TblExam.setValueAt(cboSubject.getSelectedItem().toString(), row, 5);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnManageMarkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageMarkMouseClicked
        // TODO add your handling code here:
        if(btnEditDisabled == false){
            Exam e = new Exam();
            int row = TblExam.getSelectedRow();
            e.setClass_id(listClass.get(jComboBox1.getSelectedIndex()).getClassID());
            e.setCondition(Integer.parseInt(txtCondition.getText()));
            e.setTotalmark(Integer.parseInt(txtTotalMark.getText()));
            e.setName(txtExamName.getText());
            e.setSubject_id(listSubject.get(cboSubject.getSelectedIndex()).getSubject_id());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            try {
                e.setExam_date(new java.sql.Date(date.parse(txtDate.getText()).getTime()));
            } catch (ParseException ex) {
                Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            e.setExam_id(Integer.parseInt(txtExamID.getText()));  
            new MarkFrame(e,true).setVisible(true);
        }
    }//GEN-LAST:event_btnManageMarkMouseClicked

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            Date date = jDateChooser1.getDateEditor().getDate();
            SimpleDateFormat print = new SimpleDateFormat("yyyy-MM-dd");
            txtDate.setText(print.format(date));
        } else {
            
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ExamFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblExam;
    private javax.swing.JLabel btnAdd;
    private javax.swing.JLabel btnClear;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnManageMark;
    private javax.swing.JComboBox<String> cboSubject;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCondition;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtExamID;
    private javax.swing.JTextField txtExamName;
    private javax.swing.JTextField txtTotalMark;
    // End of variables declaration//GEN-END:variables
    private void loadClassForCombo(){
        ResultSet rs;
        ClassDB classDB = new ClassDB();
        cboClassModel.removeAllElements();
        rs = classDB.getAllClass();
        try {
            while(rs.next()){
                Classes.Class c = new Classes.Class();
                c.setClassID(rs.getInt("class_id"));
                c.setName(rs.getString("name"));
                listClass.add(c);
                cboClassModel.addElement(c);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadSubjectForCombo(){
        ResultSet rs;
        SubjectDB subjectDB = new SubjectDB();
        cboSubjectModel.removeAllElements();
        rs = subjectDB.getAllActiveSubject();
        try {
            while(rs.next()){
                Subject s = new Subject();
                s.setSubject_id(rs.getInt("subject_id"));
                s.setName(rs.getString("name"));
                listSubject.add(s);
                cboSubjectModel.addElement(s.getName());
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void loadDataForTable(){
        ResultSet rs;
        int selectedClass = jComboBox1.getSelectedIndex();
        int classID = listClass.get(selectedClass).getClassID();
        rs = new ExamDB().getAllExamByClassID(classID);
        try {
            while(rs.next()){
                Object[] data ={rs.getInt("exam_id"), rs.getString("name"), 
                    rs.getString("exam_date"), rs.getInt("totalmark"), 
                    rs.getInt("condition"), rs.getString("subject_name")};
                tableModel.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ExamFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private boolean validateForm(){
        boolean isValidated = false;
        if("".equals(txtExamName.getText()) || "".equals(txtDate.getText()) || 
                "".equals(txtCondition.getText()) || "".equals(txtTotalMark.getText())){
            JOptionPane.showMessageDialog(null, "Please fill up the form first!");
        }
        else if(Integer.parseInt(txtCondition.getText())<=0 || Integer.parseInt(txtCondition.getText()) > 100){
            JOptionPane.showMessageDialog(null, "Condition must be greater than 0 and smaller than 100!");            
        }
        else if(Integer.parseInt(txtTotalMark.getText())<=0){
            JOptionPane.showMessageDialog(null, "Total mark cannot be smaller than 0!");
        }
        else{
            isValidated = true;
        }
        return isValidated;
    }
}
